Models/CounterModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace TestAssignmentAvSoft.Models
{
    public class CounterModel
    {
        [Key]
        public Guid Guid { get; set; }
        public int Id { get; set; }
        public int Value { get; set; }
    }
}

Models/CounterSpecialModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TestAssignmentAvSoft.Models
{
    public class CounterSpecialModel
    {
        [Key]
        public Guid Guid { get; set; }

        public int Id { get; set; }

        public int Count { get; set; }

        public int CountMoreThenOne { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace TestAssignmentAvSoft.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CounterSpecialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TestAssignmentAvSoft.Infrastructure;
using TestAssignmentAvSoft.Models;
using TestAssignmentAvSoft.Providers;

namespace TestAssignmentAvSoft.Controllers
{
    public class CounterSpecialController : Controller
    {
        private readonly ICounterProvider _counterProvider;

        public CounterSpecialController(ICounterProvider counterProvider)
        {
            _counterProvider = counterProvider;
        }

        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Запрос, возвращающий количество записей по столбцу id и записей, и счетчик значений больше единицы.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Get()
        {
           var counterSpecials =  _counterProvider.GetCounterSpecialModels();

           return View("Get", counterSpecials);
        }
    }
}

Pages/Counter/Get.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TestAssignmentAvSoft.Infrastructure;
using TestAssignmentAvSoft.Models;
using TestAssignmentAvSoft.Providers;

namespace TestAssignmentAvSoft.Pages.Counter
{
    public class GetModel : PageModel
    {
        private readonly ICounterProvider _counterProvider;

        public GetModel(ICounterProvider counterProvider)
        {
            _counterProvider = counterProvider;
        }

        public IQueryable<CounterModel> CounterModel { get;set; }

        public async Task OnGetAsync()
        {
            CounterModel = await _counterProvider.GetCounter();
        }
    }
}

Pages/Counter/Insert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using TestAssignmentAvSoft.Infrastructure;
using TestAssignmentAvSoft.Models;
using TestAssignmentAvSoft.Providers;

namespace TestAssignmentAvSoft.Pages.Counter
{
    public class InsertModel : PageModel
    {
        private readonly ICounterProvider _counterProvider;

        public InsertModel(ICounterProvider counterProvider)
        {
            _counterProvider = counterProvider;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public CounterModel CounterModel { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _counterProvider.Insert(CounterModel);

            return RedirectToPage("./Index");
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestAssignmentAvSoft.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestAssignmentAvSoft.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Counter/Get.cshtml
@page
@model TestAssignmentAvSoft.Pages.Counter.GetModel

@{
    ViewData["Title"] = "Get";
}

<h2>Get</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CounterModel.FirstOrDefault().Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CounterModel.FirstOrDefault().Value)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.CounterModel) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
        </tr>
}
    </tbody>
</table>

Pages/Counter/Insert.cshtml
@page
@model TestAssignmentAvSoft.Pages.Counter.InsertModel

@{
    ViewData["Title"] = "Get";
}

<h2>Get</h2>

<h4>CounterModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CounterModel.Id" class="control-label"></label>
                <input asp-for="CounterModel.Id" class="form-control" />
                <span asp-validation-for="CounterModel.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CounterModel.Value" class="control-label"></label>
                <input asp-for="CounterModel.Value" class="form-control" />
                <span asp-validation-for="CounterModel.Value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Main page";
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestAssignmentAvSoft</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">TestAssignmentAvSoft</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/Counter/Get">Get</a></li>
                    <li><a asp-page="/Counter/Insert">Insert</a></li>
                    <li><a asp-area="" asp-controller="CounterSpecial" asp-action="Get">GetSpecial</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - TestAssignmentAvSoft</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/CounterSpecial/Get.cshtml
@model List<TestAssignmentAvSoft.Models.CounterSpecialModel>

@{
    ViewBag.Title = "Counter list";
    Layout = "_Layout";
}

<h2>Counter list</h2>

<table class="table-fill">
    <thead>
    <th>Id</th>
    <th>Count</th>
    <th>CountMoreTheNone</th>
        </thead>
    <tbody class="table-hover">
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Count</td>
                <td>@item.CountMoreThenOne</td>
            </tr>
        }
    </tbody>
</table>